version: '3'
services:
  backend-services:
    image: kalah-backend
    ports:
     - "8080:8080"
  frontend:
    image: kalah-frontend
    deploy:
      mode: replicated
      replicas: 1
    ports:
    - "3060:3060"

