version: '3'
services:
  backend-services:
    image: bahadiryilmaz/kalah-backend
    deploy:
          mode: replicated
          replicas: 1
    ports:
     - "8080:8080"
  frontend:
    image: bahadiryilmaz/kalah-frontend
    ports:
    - "3060:3060"

